environment:
  NOT_CRAN: "true"
  R_URL: "https://cran.rstudio.com/bin/windows/base/R-3.6.1-win.exe"

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12"

# Download and install R binary
#  - ps: |
#      (new-object net.webclient).DownloadString("http://cran.rstudio.com/bin/windows/base/") -match 'href="(R-[0-9.]*[a-zA-Z]*-win.exe)"';
#      (new-object net.webclient).DownloadFile($("http://cran.rstudio.com/bin/windows/base/"+$matches[1]),"C:\projects\R-binary.exe")
  - ps: (new-object net.webclient).DownloadFile(
        $env:R_URL,
        "C:\projects\R-binary.exe")
  - C:\projects\R-binary.exe /VERYSILENT /DIR=C:\projects\R

  # Download miktex portable

  # - ps: (new-object net.webclient).DownloadFile(
  #     "http://mirrors.ctan.org/systems/win32/miktex/setup/windows-x86/portable-miktex.exe",
  #     "C:\projects\miktex-portable.exe")
  # - C:\projects\miktex-portable.exe --unattended --auto-install=yes --portable=c:\miktex
  # - set "PATH=%PATH%;c:\miktex\texmfs\install\miktex\bin\x64"
  # autoinstall latex packages (0=no, 1=autoinstall, 2=ask)
  # this adds this to the registry!
  # - initexmf --set-config-value "[MPM]AutoInstall=1"

  - set PATH=C:\projects\R\bin\x64;%PATH%

  # Use tinytex for latex

  - Rscript -e "install.packages('tinytex', repos='http://cran.rstudio.com/'); tinytex::install_tinytex(force=TRUE); tinytex:::install_yihui_pkgs()"
  - set PATH=%APPDATA%\\TinyTeX\\bin\\win32;%PATH%

  # Download and install Rtools

  - ps: (new-object net.webclient).DownloadFile(
      "https://cran.rstudio.com/bin/windows/Rtools/Rtools35.exe",
      "C:\projects\rtools.exe")
  # - C:\projects\rtools.exe /S /D=C:\Rtools
  - C:\projects\rtools.exe /VERYSILENT /DIR=C:\Rtools

  - set PATH=c:\Rtools\bin;c:\Rtools\gcc-4.6.3\bin;%PATH%

build_script:
# Need to convert from shallow to complete for Pkg.clone to work
#  - IF EXIST .git\shallow (git fetch --unshallow)
#  - C:\projects\julia\bin\julia -e "versioninfo();
#      Pkg.clone(pwd(), \"RCall\"); Pkg.build(\"RCall\")"

# Not build vignettes
- rm -rf vignettes
- Rscript -e "d <- read.dcf('DESCRIPTION'); d[, colnames(d) == 'VignetteBuilder'] <- NA; write.dcf(d, 'DESCRIPTION')"

- Rscript -e "sessionInfo()"
- Rscript -e "install.packages(\"testthat\", repos=\"http://cran.rstudio.com/\")"
- Rscript -e "install.packages(\"knitr\", repos=\"http://cran.rstudio.com/\")"
- Rscript -e "install.packages(\"rmarkdown\", repos=\"http://cran.rstudio.com/\")"

test_script:
- R CMD build .
- R CMD check *tar.gz --no-multiarch

on_finish:
# uncomment to enable RDP to Appveyor
# - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
