environment:
  NOT_CRAN: "true"
  R_URL: "https://cran.rstudio.com/bin/windows/base/R-4.0.2-win.exe"
  _R_CHECK_FORCE_SUGGESTS_: "false"
  JULIA_HOME: "C:\\projects\\julia\\v1.5.0\\bin"

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
  - ps: "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12"

# Download and install R binary
#  - ps: |
#      (new-object net.webclient).DownloadString("http://cran.rstudio.com/bin/windows/base/") -match 'href="(R-[0-9.]*[a-zA-Z]*-win.exe)"';
#      (new-object net.webclient).DownloadFile($("http://cran.rstudio.com/bin/windows/base/"+$matches[1]),"C:\projects\R-binary.exe")
  - ps: (new-object net.webclient).DownloadFile(
        $env:R_URL,
        "C:\projects\R-binary.exe")
  - C:\projects\R-binary.exe /VERYSILENT /DIR=C:\projects\R
  - set PATH=C:\projects\R\bin;%PATH%

  # Download miktex portable

  # - ps: (new-object net.webclient).DownloadFile(
  #     "http://mirrors.ctan.org/systems/win32/miktex/setup/windows-x86/portable-miktex.exe",
  #     "C:\projects\miktex-portable.exe")
  # - C:\projects\miktex-portable.exe --unattended --auto-install=yes --portable=c:\miktex
  # - set "PATH=%PATH%;c:\miktex\texmfs\install\miktex\bin\x64"
  # autoinstall latex packages (0=no, 1=autoinstall, 2=ask)
  # this adds this to the registry!
  # - initexmf --set-config-value "[MPM]AutoInstall=1"

  # Use tinytex for latex

  - Rscript -e "install.packages('tinytex', repos='http://cran.rstudio.com/'); tinytex::install_tinytex(force=TRUE); tinytex:::install_yihui_pkgs()"
  - set PATH=%APPDATA%\\TinyTeX\\bin\\win32;%PATH%

  # Download and install Rtools

  - ps: (new-object net.webclient).DownloadFile(
      "https://cran.r-project.org/bin/windows/Rtools/rtools40-x86_64.exe",
      "C:\projects\rtools.exe")
  # - C:\projects\rtools.exe /S /D=C:\Rtools
  - C:\projects\rtools.exe /VERYSILENT /DIR=C:\Rtools
  - set PATH=C:\Rtools\usr\bin;%PATH%

build_script:
  - rm -rf vignettes
  - ps: |
      Rscript -e "d <- read.dcf('DESCRIPTION'); d[, colnames(d) == 'VignetteBuilder'] <- NA; write.dcf(d, 'DESCRIPTION')"
      Rscript -e 'sessionInfo()'
      Rscript -e 'install.packages("testthat", "knitr", "rmarkdown", "Rcpp", "devtools", repos="http://cran.rstudio.com/")'
      Rscript -e 'library(devtools); devtools::load_all("."); library(JuliaCall); JuliaCall::install_julia("C:\\projects\\julia")'

test_script:
  - R CMD build .
  - R CMD check *tar.gz --no-multiarch

on_finish:
  # uncomment to enable RDP to Appveyor
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
